# Generated by Django 2.2.4 on 2019-08-15 10:21

from django.db import migrations

import phonenumbers


def unify_phonenumbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone_pure = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(phone_pure):
            flat.owner_phone_pure = phonenumbers.format_number(phone_pure, phonenumbers.PhoneNumberFormat.E164)
            flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0008_auto_20190815_1302'),
    ]

    operations = [
        migrations.RunPython(unify_phonenumbers)
    ]
