# Generated by Django 2.2.4 on 2019-08-15 11:52

from django.db import migrations


def make_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.create(
            full_name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_phone_pure=flat.owner_phone_pure
        )
        flat.owned_by.add(owner)


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [migrations.RunPython(make_owner)
    ]
